version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - logging

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=["http://0.0.0.0:9200"]
    ports:
      - "5601:5601"
    networks:
      - logging
    depends_on:
      - elasticsearch

networks:
  logging: